### ISSUE TITLE
Use different serial port

### ISSUE THREAD

**Issue by Actpohomoc** [UedaTakeyuki/mh-z19#12]
I have used already built-in serial connection for RFID reader. Is there way to use USB serial device to get information from CO2 sensor?
Or implement software serial like we have it on Arduino.

**Comment by UedaTakeyuki** [comment]
Hi Actpohomoc,

Thank you for your interesting and helpful suggestive question!
I.M.H.O. in the aspect of the software, the main difference in RPi UART  and USB serial is just a tty device name (and some other parameters). What tty device do you see for the USB serial? Also, do you see the appropriate serial parameter?

**Comment by TBR-BRD** [comment]
Hello, i have the same problem. ls -l /dev/serial/by-id => lrwxrwxrwx 1 root root 13 Jul 29 18:56 usb-FTDI_FT232R_USB_UART_A50285BI-if00-port0 -> ../../ttyUSB0
Which config must be edit to use this USB UART module to read the data?
Thank you

**Comment by UedaTakeyuki** [comment]
HI TBR-BRD

How was /dev/ttyUSB0?
How to find USB serial is:

1. Without USB serial, look ls /dev
2. Connect USB serial, then look ls /dev again, find an added one must be the device file of USB serial.

**Comment by UedaTakeyuki** [comment]
Hi TBR-BRD,

I've added **--serial_device** option for specifying a specific serial device.
Please try it with the latest version of the library as follows:

```
sudo python -m mh_z19 --serial_device /dev/ttyUSB0
```

Thanks, and sorry for my late reaction due to my summer vacation. Now, I've returned back home.

**Comment by TBR-BRD** [comment]
Hi, thank you for your work. I will test it later this week. Thanks

**Comment by UedaTakeyuki** [comment]
no feedback.
