### ISSUE TITLE
Funcion abc_off()

### ISSUE THREAD

**Issue by temycor** [UedaTakeyuki/mh-z19#23]
Hola a todos. Tengo una duda:

Si escribo en idle python3:

>>> import mh_z19
>>>mh_z19.abc_off()

¿Se desactiva el autocalibrado del sensor?

Muchas gracias por su gran trabajo.

**Comment by UedaTakeyuki** [comment]
Hola temycor!

Si usted entiende.
Sin embargo, no lo he probado porque no tengo mh_z19B, pero no he recibido ningún informe de que mh_z19.abc_off () no funcione.
Si la caribración automática no está desactivada ejecutando mh_z19.abc_off (), háganoslo saber.

**Comment by temycor** [comment]
Hi, thank you for your quick answer.

Of course, i have yet the sensor mhz19b but i have to buy the raspberry pi soon. When i buy it, i will write you. 

Buy.

**Comment by UedaTakeyuki** [comment]
long time no feedback.

**Comment by temycor** [comment]
Excuse me, I haven't bought my raspberry pi yet. :(
