### ISSUE TITLE
Raspberry 4 Support

### ISSUE THREAD

**Issue by iperniaf** [UedaTakeyuki/mh-z19#29]
Hi,
I'm using your lib with a rpbi 4 and it needs some fixes.
¿Can I contribute to the community fixing them?

**Comment by UedaTakeyuki** [comment]
Would you please tell me which problem and fixing?
I've not heard of any problem with RRi4.

**Comment by iperniaf** [comment]
On mh_z19.py script, line 39, you select serial port using strict Rpi model.
Rpi4 model is not listed, so it tries to use ttyAMA0 port, and the correct one is ttyS0

**Comment by UedaTakeyuki** [comment]
Weird, line 29 can't be passed because Raspberry Pi OS must have **/dev/serial0** as a symbolic link.
Do you use other OS?

**Comment by iperniaf** [comment]
yes, i'm using a raspberry image on a docker container running on balena etcher OS

**Comment by UedaTakeyuki** [comment]
I see!

So, the necessary fix might be as following 2.

1. Add RPi4 definition to https://github.com/UedaTakeyuki/getrpimodel
2. Add "4 Model B" to line 31

right?

**Comment by UedaTakeyuki** [comment]
> Add RPi4 definition to https://github.com/UedaTakeyuki/getrpimodel

Sorry, this was my missunderstanding, now RPi4 is in getrpimodel.
So, nesessary fix might be only #2.

I welcome your pull request!

**Comment by iperniaf** [comment]
I have no permision to push my changes on a new branch

**Comment by UedaTakeyuki** [comment]
Not push directory, instead, you can make **pull request**.

**Comment by iperniaf** [comment]
done!
I have an extrage behavior. 
I'm running your script with serial_console_untouched=True
Sometimes the scripts runs ok, but other times it returns "None"
![image](https://user-images.githubusercontent.com/39204168/112322821-84338100-8cb1-11eb-8fb5-1b9e06066d2b.png)
Can you imagine what's happening?

**Comment by UedaTakeyuki** [comment]
No idea, sorry.

**Comment by UedaTakeyuki** [comment]
Hi iperniaf,

I've fixed it and updated it to version 3.0.2 both github and pypi.
Would you please try it? thank you.

**Comment by UedaTakeyuki** [comment]
longtime no feedback
