### ISSUE TITLE
"null" on screen.

### ISSUE THREAD

**Issue by spidermancan** [UedaTakeyuki/mh-z19#32]
I have the MH-Z19 attached to the ANAVI phat, on a raspberry pi zero w. I installed the python modules and enabled the i2c interface. I found a similar help request, but I tried all of the different codes and nothing happened. 

THis is my wiring:
Tx-Rx
Rx-Tx
vin-3.3v
GND-GND
When I type in`sudo python -m mh_z19` this output is null. 
![image](https://user-images.githubusercontent.com/91803892/135731077-380e816a-4f81-4a94-83e8-e767c773992a.png)

**Comment by UedaTakeyuki** [comment]
Hi spidermancan,


- try pull up, refer [issue 26](https://github.com/UedaTakeyuki/mh-z19/issues/26#issuecomment-744039360)

or 

- try [PWM](https://github.com/UedaTakeyuki/mh-z19/wiki/PWM-support.)

**Comment by UedaTakeyuki** [comment]
No feedback for 5 days.
