### ISSUE TITLE
mh-z19.setHumidity()?

### ISSUE THREAD

**Issue by Proktologe** [UedaTakeyuki/mh-z19#46]
Hi, 

is it possible to <set> the humidity and the temperature with your library to increase the measurement accuracy and get a better Co2 result?

**Comment by UedaTakeyuki** [comment]
Hi proktologe,

Interesting idea.
How can increase the accuracy with additional humidity and temperature?
Any informations, sugestions, or pointings are welcome. Thank you!

**Comment by UedaTakeyuki** [comment]
6 days no feedback.
