### ISSUE TITLE
Typo in Wiki module documentation

### ISSUE THREAD

**Issue by bceylon** [UedaTakeyuki/mh-z19#47]
Module documentation [page](https://github.com/UedaTakeyuki/mh-z19/wiki/module#xero_point_calibrationserial_console_untouchedfalse) has small typo, it has 'xero_point_calibration' as a function name while it should be 'zero_point_calibration'.

**Comment by UedaTakeyuki** [comment]
Hi bceylon,

Thank you for telling me this typo!
I've fixed it. I really appreciate your lovely contribution.

**Comment by UedaTakeyuki** [comment]
close.
