### ISSUE TITLE
No Data & Serial Port problems

### ISSUE THREAD

**Issue by wh1t3chr1s** [UedaTakeyuki/mh-z19#48]
Hallo, 
I'm very new to all of this, so sorry in advance.

-Raspberry Pi 4 /w MH_Z19C
-I installed it via "pip install".
-I've enabled the serial port hardware in raspi-config as well as I2C which I need for the other part of my project.
-I triple-checked the wiring.
-The red led is blinking.
-I used "chmod 777" (just in case) for both /dev/ttyS0 and /dev/AMA0
-I disabled bluetooth just like one person of the other issues stated that it worked for them.
-After I used _mh_z19.read_all()_ once, it reset all the permissions for ttyS0 back to what it was before. Therefore I get this after using it again:
![helplol](https://user-images.githubusercontent.com/57096204/198554291-21023285-0f85-4892-8124-6b5607aaa32e.PNG)

Help? ^^°

**Comment by UedaTakeyuki** [comment]
Hi wh1t3chr1s,

Would you please try ***mh_z19.read_all(true)*** instead of ***mh_z19.read_all()*** and tell me the result, thx!

**Comment by wh1t3chr1s** [comment]
I don't know WHY, but  mh_z19.read_all() works now for some reason as well as the (True) version that you just suggested.

**Comment by wh1t3chr1s** [comment]
The only thing thats weird is that the temperature doesn't seem to be correct. I have two other ways of getting my temperature, both tell 4 degrees cooler.

**Comment by UedaTakeyuki** [comment]
The temperature returned by read_all() is just an expedient value, not a universal truth.
It's just computed as [TT - 40](https://github.com/UedaTakeyuki/mh-z19/blob/master/mh_z19.py#L129) what TT is for the sensor internal and related to ambient temperature.
Under several environments, -40 works as a good supplement, but if it doesn't fit in your environment, you can use it with adding your complement +4.

More detail about [TT](https://github.com/UedaTakeyuki/mh-z19/wiki/Is-the-undocumented-TT-value-on-the-responses-of-command-0x86-really-related-to-the-ambient-temperature%3F).

**Comment by UedaTakeyuki** [comment]
5 day no feedback.
