### ISSUE TITLE
Still return {} after using pull-up resistor and change freq = 250 and enable_uart = 1

### ISSUE THREAD

**Issue by EfraimManurung** [UedaTakeyuki/mh-z19#51]
Hallo Mr. Takeyuki and everyone,

I still have a problem with my MH-Z19C sensor, it is still always treturn {}, can someone help me? is it compatible for the MH-Z19C or only for B? I already read many blogs and github and I cannot solve my problem

I did my work on Raspberry Pi 5, and I also tried it on my 3+ but still not working. I already tried the pull-up resistor both for RX or TX pins. 

![WhatsApp Image 2024-04-06 at 2 18 09 AM](https://github.com/UedaTakeyuki/mh-z19/assets/61244115/26c50155-691a-46b0-a086-66c4f6c54184)
<img width="791" alt="return {}" src="https://github.com/UedaTakeyuki/mh-z19/assets/61244115/0a7dbb1c-c35f-4e09-aa71-674fbdbaf51e">

Thank you so much.

**Comment by UedaTakeyuki** [comment]
Hi Efraim,

There is a track record of operation with MH-Z19C.
The MH-Z19 sensor module requires a few minutes **preheat** time. In case not preheated, you may get the value after preheated.

**Comment by EfraimManurung** [comment]
Thank you for your response Mr. Takeyuki. I tried again after pre-heating for more than 10 minutes, it is working using ESP32/Arduino Uno but it's not working for the Raspberry Pi. I already followed all your procedures Mr. Takeyuki. Are there other things that I can do?

and what do you mean by a track record of operation with MH-Z19C? 

<img width="498" alt="return {} 2" src="https://github.com/UedaTakeyuki/mh-z19/assets/61244115/0e694676-44c4-4af7-a86b-4a3d8330c69e">

**Comment by UedaTakeyuki** [comment]
Ah, I mean I don't use this with type C, someone reported that this library worked well with type C.
By the way, the return  value ``{}`` without any error message means that the serial interface is connected normally. This library sent command to the sensor normally, and no response returned.

**Comment by EfraimManurung** [comment]
I already tried it using a different serial Dr. Takeyuki, do you have other solutions?

Oh so do you mean this library only intended for MH-Z19B not for series C? 

<img width="808" alt="return {} 3" src="https://github.com/UedaTakeyuki/mh-z19/assets/61244115/173e0089-abec-45ad-b351-3376e4ec11ed">

**Comment by UedaTakeyuki** [comment]
Hi Efraim,

Not only with type B but also with type C.
I heard a lot of reports that this run with MH-Z19C.

What happens if you run it with ``/dev/serial1``? Not with **serial10**.

**Comment by EfraimManurung** [comment]
Dear Dr. Takeyuki, thank you for your response

I believe it is working with **serial0** because **serial1** I cannot access it. Do you have another suggestion? I also reinstall the OS of Raspberry Pi 5 but still not working. 
<img width="788" alt="return {} 4" src="https://github.com/UedaTakeyuki/mh-z19/assets/61244115/7a9cc687-3145-4cec-b686-095705cf117d">

**Comment by EfraimManurung** [comment]
Dear Dr. Takeyuki, I solved it! finally, after I tried using Arduino Uno, I realised there is a different address for Raspberry Pi 5 and you're right. I searched different addresses and matched with /dev/tty/AMA0

![return {} 6](https://github.com/UedaTakeyuki/mh-z19/assets/61244115/4430a772-700a-43ea-a2bd-d1a0e1fd1154)

<img width="917" alt="return {} 5" src="https://github.com/UedaTakeyuki/mh-z19/assets/61244115/f953a189-434b-4945-86cf-f76a608ab1db">

Thank you so much for your time! I hope this thread will be helpful for someone too.

Efraim.

**Comment by EfraimManurung** [comment]
dear Dr. Takeyuki, 

I have last question, for "sudo python3 -m mh_z19 --all --serial_device /dev/tty
AMA0"

how do I set up the program? is there a parameter for it to setup the serial_dev?

the program like in the example
"import mh_z19

mh_z19.read_all()"

**Comment by UedaTakeyuki** [comment]
I'm so glad to hear that your problem was resolved. I appreciate your patient cooperation in investigating and fixing this issue.

Also, thank you for your reporting that there is ``No documentation`` to change serial device. I've added it as [set_serialdevice(device)](https://github.com/UedaTakeyuki/mh-z19/wiki/module#set_serialdevicedevice).

You can use this library in your program as follows:

```
import mh_z19

mh_z19.set_serialdevice("/dev/ttyAMA0")
mh_z19.read_all()
```

**Comment by EfraimManurung** [comment]
Dear dr. Takeyuki, it works! thank you very much for your help. I can continue working on my thesis project. 

<img width="675" alt="return {} 7" src="https://github.com/UedaTakeyuki/mh-z19/assets/61244115/d275d9d5-f032-475f-baf6-da0ef5990d8f">

**Comment by UedaTakeyuki** [comment]
I hope your thesis project is going well. I would be pleased to see your great thesis once it is completed.
